### ISSUE TITLE
Why check cache-control: no-cache?

### ISSUE THREAD

**Issue by abbr** [jshttp/fresh#16] opened 2014-12-21 01:27 UTC
Hi,
If a request contains both header `cache-control: no-cache` and a fresh etag, _fresh_ will mark the request not fresh. I don't understand why. According to [w3.org](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.1)'s explanation about no-cache: _If the no-cache directive does not specify a field-name, then a cache MUST NOT use the response to satisfy a subsequent request without successful revalidation with the origin server_. This directive only tells a proxy to revalidate with the server. It shouldn't be used by origin server to determine a cached content is stale, which is the job of etag and last modified timestamp header.

I encountered this problem when using IE XDomainRequest. IE added `cache-control: no-cache` automatically if previous response has header `Cache-Control: max-age=0` and there is no way to disable the request header.

**Comment by alexandrethsilva** [comment] 2015-07-30 09:56
Hi @dougwilson, I believe this issue is directly related to Safari's blank pages when sending a ```Cache-Control: max-age=0```, no?
Do you have any news on this? I currently have the fix on my local version, but it's of course the worst possible solution and it would be nice to know that I can just have a correct synced version with the repo.

For what I understood from [**the spec**](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.3) you guys are mentioning, Safari is not behaving wrongly... So I wonder what's the possible solution if not here.

**Comment by dougwilson** [comment] 2015-07-30 16:42
> So I wonder what's the possible solution if not here.

The issue is a bug in Safari. The reason it ends up with a blank page is due to a race condition within it's own client-side caching mechanism. I believe this may be fixed in the very latest versions of Safari, but I do not know. There is nothing we can do here to help Safari overcome it's bug without user-agent sniffing, which we will not do. 

Your best solution is to use the https://github.com/Dakuan/jumanji module.

**Closed** 2017-02-05 03:45 UTC
Labels: docs, low priority, question
