### ISSUE TITLE
nginx transforms ETag to Weak Etag on gzip => module doesn't work

### ISSUE THREAD

**Issue by iliakan** [jshttp/fresh#17] opened 2015-05-11 07:14 UTC
I explored a bit trying to find out why this module doesn't work for me.

The first issue I found was weak etags. The module does not support them.

The second was kind of astonishing for me cause I saw: `return !! (etagMatches && notModified);` at the end.

`ETag` and `Last-Modified` are two different mechanisms. If *any of them* is satisfied, the request cache is "fresh". Not both of them. So there must be `return !! (etagMatches || notModified);` unless you point out the sane reason :/

**Comment by dougwilson** [comment] 2015-05-11 07:19
> unless you point out the sane reason :/

The variables are simply not named well. You can look at the tests to see both are not required. If you give both in the request, both must match.

There isn't much I can really help here unless you provide concrete examples.

**Comment by dougwilson** [comment] 2015-05-11 07:29
Basically all this library is is a function that tales two objects and gives a boolean. In order to help, just paste here a call to fresh and state what you expect the boolean to be and I can consult RFC 723x to determine what the correct behavior should be.

**Comment by iliakan** [comment] 2015-05-11 07:37
Hi Doug, thanks a lot for the quick response.
After a more in-depth look I see that the logic is actually `||`. 

So that's only a weak etags problem.

I renamed the issue because of that.

In my case, I use Nginx which serves static files and gzips content from node.
About 10 months ago there was a change in Nginx https://twitter.com/samsaffron/status/486387129165942784, which basically changes Strong Etags to Weak Etags (prepends W/) when gzipping.

So all content is actually served with weak etags. Guess, the module could just transform a weak etag into a normal etag (strip initial W/) and then do it's job?

**Comment by dougwilson** [comment] 2015-05-11 07:40
Interesting. I'll check it out tomorrow (going to sleep in the US right now), but yes, the weak etag matching from RFC 7232 are not yet implemented, so essentially it only does strong matching (or weak matching if the Node.js server is sending the weak etag).

**Comment by dougwilson** [comment] 2015-05-12 01:57
Apparently this is a duplicate of #11

**Closed** 2015-05-12 03:03 UTC
Labels: enhancement

**Comment by dougwilson** [comment] 2015-05-12 03:25
@iliakan let me know if the change on `master` fixes the issue for you and I can then cut a release.

**Comment by iliakan** [comment] 2015-05-12 06:07
Hi Doug,

Thanks, works fine now.

**Comment by dougwilson** [comment] 2015-05-12 15:10
Awesome, @iliakan , thanks for confirming! I just published to npm as 0.3.0 :)
